// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBle_Q3JlvoWf0M5aivMnU6PDfBqDvj0gk',
    appId: '1:999402611749:web:dcb422cada383db007cbcc',
    messagingSenderId: '999402611749',
    projectId: 'weather-application-964ca',
    authDomain: 'weather-application-964ca.firebaseapp.com',
    storageBucket: 'weather-application-964ca.appspot.com',
    measurementId: 'G-BQ9EEVTTVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zIr9g7lP338V3Wo_EK4bBEFMBzQzVEM',
    appId: '1:999402611749:android:2697c1f058c06e8207cbcc',
    messagingSenderId: '999402611749',
    projectId: 'weather-application-964ca',
    storageBucket: 'weather-application-964ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs5-obzNYlWL8HlVA_6G7EUgYneXbdbB8',
    appId: '1:999402611749:ios:ef357acbfc3e34b707cbcc',
    messagingSenderId: '999402611749',
    projectId: 'weather-application-964ca',
    storageBucket: 'weather-application-964ca.appspot.com',
    iosClientId: '999402611749-tc754r39u0utnjbgfur17il66a2db9o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs5-obzNYlWL8HlVA_6G7EUgYneXbdbB8',
    appId: '1:999402611749:ios:ef357acbfc3e34b707cbcc',
    messagingSenderId: '999402611749',
    projectId: 'weather-application-964ca',
    storageBucket: 'weather-application-964ca.appspot.com',
    iosClientId: '999402611749-tc754r39u0utnjbgfur17il66a2db9o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  
}
